spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes_development
    username: yuriyalekseyev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    banner-mode: off
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG